---
- name: sysctl
  tags:
    - sysctl
  block:
    - name: net.ipv4.tcp_l3mdev_accept
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.tcp_l3mdev_accept
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.udp_l3mdev_accept
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.udp_l3mdev_accept
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.fib_multipath_hash_policy
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.fib_multipath_hash_policy
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.conf.default.arp_accept
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.default.arp_accept
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.conf.default.arp_announce
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.default.arp_announce
        value: 2
        state: present
        reload: yes
    - name: net.ipv4.conf.default.arp_filter
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.default.arp_filter
        value: 0
        state: present
        reload: yes
    - name: net.ipv4.conf.default.arp_ignore
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.default.arp_ignore
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.conf.default.arp_notify
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.default.arp_notify
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.neigh.default.base_reachable_time_ms
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.neigh.default.base_reachable_time_ms
        value: 150000
        state: present
        reload: yes
    - name: net.ipv4.neigh.default.delay_first_probe_time
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.neigh.default.delay_first_probe_time
        value: 300
        state: present
        reload: yes
    - name: net.ipv4.neigh.default.gc_stale_time
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.neigh.default.gc_stale_time
        value: 5
        state: present
        reload: yes
    - name: net.ipv4.neigh.default.gc_thresh1
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.neigh.default.gc_thresh1
        value: 5
        state: present
        reload: yes
    - name: net.ipv4.ip_forward
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes
    - name: net.ipv4.conf.all.proxy_arp
      sysctl:
        sysctl_file: /etc/sysctl.d/99-sysctl.conf
        name: net.ipv4.conf.all.proxy_arp
        value: 1
        state: present
        reload: yes
